"""add liveness columns to screenings

Revision ID: 5f9a3c21b7e4
Revises: eb993e3a880b
Create Date: 2026-09-06 18:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9a3c21b7e4'
down_revision: Union[str, None] = 'eb993e3a880b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('liveness_status', sa.String(length=40), nullable=False, server_default='NOT_CHECKED'))
    op.add_column('screenings', sa.Column('liveness_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'liveness_score')
    op.drop_column('screenings', 'liveness_status')
    # ### end Alembic commands ###