"""add dashboard columns to screenings and users

Revision ID: c7a1f2b3c4d5
Revises: 5f9a3c21b7e4
Create Date: 2026-09-11 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a1f2b3c4d5'
down_revision: Union[str, None] = '5f9a3c21b7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('applicant_name', sa.String(length=120), nullable=True))
    op.add_column('screenings', sa.Column('document_number', sa.String(length=64), nullable=True))
    op.add_column('screenings', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.add_column('screenings', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index('ix_screenings_document_number', 'screenings', ['document_number'], unique=False)

    op.add_column('users', sa.Column('officer_id', sa.String(length=50), nullable=True))
    op.create_index('ix_users_officer_id', 'users', ['officer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_officer_id', table_name='users')
    op.drop_column('users', 'officer_id')

    op.drop_index('ix_screenings_document_number', table_name='screenings')
    op.drop_column('screenings', 'notes')
    op.drop_column('screenings', 'country_code')
    op.drop_column('screenings', 'document_number')
    op.drop_column('screenings', 'applicant_name')
    # ### end Alembic commands ###
