"""add watchlist entries table

Revision ID: d4e9b8a7f6c5
Revises: d8b2e4f6a1c3
Create Date: 2026-09-20 01:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e9b8a7f6c5'
down_revision: Union[str, None] = 'd8b2e4f6a1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=False),
    sa.Column('document_number_normalized', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_doc_number_normalized', 'watchlist_entries', ['document_number_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_doc_number_normalized', table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    # ### end Alembic commands ###