"""remove pii columns from screenings table

Revision ID: d8b2e4f6a1c3
Revises: c7a1f2b3c4d5
Create Date: 2026-09-11 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b2e4f6a1c3'
down_revision: Union[str, None] = 'c7a1f2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_screenings_document_number', table_name='screenings')
    op.drop_column('screenings', 'country_code')
    op.drop_column('screenings', 'document_number')
    op.drop_column('screenings', 'applicant_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('applicant_name', sa.String(length=120), nullable=True))
    op.add_column('screenings', sa.Column('document_number', sa.String(length=64), nullable=True))
    op.add_column('screenings', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.create_index('ix_screenings_document_number', 'screenings', ['document_number'], unique=False)
    # ### end Alembic commands ###
